# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'animal'), ('D', 'daily quest')], max_length=1)),
                ('animal_name', models.CharField(max_length=30)),
                ('date_started', models.DateTimeField(verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sequence', models.IntegerField(default=0)),
                ('answer_length', models.IntegerField(default=0)),
                ('answer_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_sequence', models.IntegerField(default=0)),
                ('puzzle_size', models.IntegerField(default=0)),
                ('puzzle_characters', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordtrek.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_length', models.IntegerField(default=0)),
                ('sorted_letters', models.CharField(max_length=255)),
                ('valid_word', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordtrek.Puzzle'),
        ),
    ]
