# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('D', 'Daily Quest'), ('A', 'Animal')], max_length=1)),
                ('animal_order', models.IntegerField(default=0)),
                ('animal_name', models.CharField(max_length=30)),
                ('date_started', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'animal_order', 'date_started'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sequence', models.IntegerField(default=0)),
                ('answer_length', models.IntegerField(default=0)),
                ('answer_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['puzzle', 'answer_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_sequence', models.IntegerField(default=0)),
                ('puzzle_size', models.IntegerField(default=0)),
                ('puzzle_characters', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordtrek.Animal')),
            ],
            options={
                'ordering': ['animal', 'puzzle_sequence'],
            },
        ),
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_length', models.IntegerField(default=0)),
                ('sorted_letters', models.CharField(max_length=255)),
                ('valid_word', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sorted_letters', 'word_length', 'valid_word'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordtrek.Puzzle'),
        ),
    ]
