# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordtrek', '0002_auto_20170119_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_order', models.IntegerField(default=0)),
                ('letter_text', models.CharField(max_length=1)),
                ('letter_row', models.IntegerField(default=-1)),
                ('letter_col', models.IntegerField(default=-1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordtrek.Answer')),
            ],
            options={
                'ordering': ['answer', 'letter_order'],
            },
        ),
    ]
