# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtrek', '0004_answer_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_solved',
            field=models.CharField(blank=True, choices=[('S', 'Solved'), ('O', 'Still Open')], default='O', help_text='Has all the puzzles for this animal/daily quest been solved?', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_solved',
            field=models.CharField(blank=True, choices=[('S', 'Solved'), ('O', 'Still Open')], default='O', help_text='Have all the answers for this puzzle been solved?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('H', 'Hinted'), ('S', 'Solved')], default='U', max_length=1),
        ),
    ]
