# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtrek', '0005_auto_20170302_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('H', 'Hinted'), ('S', 'Solved')], default='U', help_text='Choose answer status.', max_length=1),
        ),
    ]
