# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtrek', '0006_auto_20170302_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['animal_solved', 'category', 'animal_order', 'date_started']},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['animal', 'puzzle_solved', 'puzzle_sequence']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('A', 'Animal'), ('D', 'Daily&nbsp;Quest')], default='A', help_text='Choose either "Animal" or "Daily Quest".', max_length=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('H', 'Hinted'), ('S', 'Solved')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_characters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_solved',
            field=models.CharField(blank=True, choices=[('S', 'Solved'), ('O', 'Still Open')], default='O', max_length=1, null=True),
        ),
    ]
