# Generated by Django 2.0 on 2017-12-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtrek', '0008_wordsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsearch',
            name='show_hide',
            field=models.CharField(choices=[('S', 'Show'), ('H', 'Hide')], default='S', help_text='Choose to show or hide this word', max_length=1),
        ),
    ]
